### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by Camwyn** [stellarwp/global-docs#1]
On https://github.com/stellarwp/global-docs/blob/main/docs/strauss-setup.md#adding-your-configuration

Should the example include a `namespace_prefix` of `Boom\Shakalaka\`?

Especially since we link to this from [Schema](https://github.com/stellarwp/schema) (for example) where we are talking about namespacing.

**Comment by borkweb** [comment]
By default, strauss defaults to using the psr-4 namespace of the project as the prefix. 💃 I think we're good on that front for the suggested configuration. If folks want to get creative beyond that, they can do so on their own :D
